CREATE TABLE IF NOT EXISTS urls (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    last_check DATE,
    last_status_code SMALLINT
);

CREATE TABLE IF NOT EXISTS url_checks (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id BIGINT REFERENCES urls(id) ON DELETE CASCADE NOT NULL,
    status_code SMALLINT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);
